# Set platform to 12.0 or higher
platform :ios, '12.0'

# CocoaPods analytics sends usage stats. If you want to disable it, uncomment the following line:
# keep_silent!

# Flutter iOS Engine Dependency
flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
